### ISSUE TITLE
Adding font link to global css.

### ISSUE THREAD

**Issue by alizahir23** [OpenSouceCode/website#7]
The font is not yet added to the project.

**Comment by irshadjsr21** [comment]
Do you mean google fonts? It's added here.

https://github.com/OpenSouceCode/website/blob/418987e76d566dcc383c3a87101280d8e91e4223/pages/_app.jsx#L11

**Comment by alizahir23** [comment]
anshul had suggested to shift to a new font family, however it isnt available on web.
